# -*- coding: utf-8 -*-
"""NFLX stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDHf4rE0trbACj7zaDu7ST3vd_eaPI5k
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io

from google.colab import files
uploaded = files.upload()

data=pd.read_csv('NFLX.csv')

data

data.shape

data.columns

data.dtypes

data.isna().sum()

data.head(50)

data.shape

data.head(1000)

data.dtypes

data.isna().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data['Date']=le.fit_transform(data['Date'])

x=data.iloc[:,:-2].values
y=data.iloc[:,-1].values

x

y

from sklearn import model_selection
model_selection.train_test_split(x,y)

from sklearn import model_selection
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
alg1=LinearRegression()

alg1.fit(x_train,y_train)

y_pred=alg1.predict(x_test)

accuracy=alg1.score(x_train,y_train)

print(accuracy)

accuracy2=alg1.score(x_test,y_pred)

print(accuracy2)

import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred,color='red')
plt.plot([y_test.min(),y_test.max()],[y_test.min(),y_test.max()],color='blue',linewidth=3)
plt.show()

#plot outputs
plt.figure(figsize=(10,6))
plt.scatter(y_test, y_pred, color='black', alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(),y_test.max()], color='blue',linewidth=3)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.grid(True)
plt.show()